### ISSUE TITLE
Are the model weights open-sourced?

### ISSUE THREAD

**Issue by heytanay** [abertsch72/unlimiformer#1]
Great work on the Unlimiformer! I was wondering if the pre-trained model weights are open-sourced yet?

**Comment by abertsch72** [comment]
Thanks for your interest in our work! 

I've just uploaded model weights to HuggingFace for most models and added [a section to the README](https://github.com/abertsch72/unlimiformer#trained-models) linking to them. I'll add further models and links to the datasets that we re-scraped as we continue releasing content!
