### ISSUE TITLE
How to reproduce the paper result?

### ISSUE THREAD

**Issue by fake-warrior8** [abertsch72/unlimiformer#11]
Hi, I'm new to summarization task, could you tell me the usage of quick reimplementation of your paper results?

**Comment by urialon** [comment]
Hi @fake-warrior8 ,
Thank you for your interest in our work!

We added new examples and command lines in our [README](https://github.com/abertsch72/unlimiformer#reproducing-the-experiments-from-the-paper---command-lines).
Can you please take a look at this and the following sections?

I'm closing this issue just to make sure we respond to all issues, but feel free to re-open it if you have any questions, we would love to help and know if there are any other problems.

Best,
Uri
