### ISSUE TITLE
Is there any example codes to run?

### ISSUE THREAD

**Issue by chenboheng** [abertsch72/unlimiformer#12]
This project is very interesting. However, I can't find the example code that can run directly. Could the authors provide some examples?

**Comment by urialon** [comment]
Hi @chenboheng ,
Thank you for your interest in our work!

We added new examples and command lines in our [README](https://github.com/abertsch72/unlimiformer#reproducing-the-experiments-from-the-paper---command-lines)
Can you please take a look at this and the following sections? 

I'm closing this issue just to make sure we respond to all issues, but feel free to re-open it if you have any questions, we would love to help and know if there are any other problems.

Best,
Uri
