### ISSUE TITLE
Typing checks fail

### ISSUE THREAD

**Issue by StrangeTcy** [abertsch72/unlimiformer#13]
Using the `CustomHfArgumentParser` to parse the `UnlimiformerArguments` from a json config which reads 
```
"layer_begin": 0,
"layer_end": "", 
``` (since json doesn't natively handle `None`) leads to a parsing error:
> error: argument --layer_end: invalid int value: ''

We can omit the `layer_end` arg from the config, but there's probably a more elegant solution

**Comment by urialon** [comment]
Hi @StrangeTcy ,
Thank you for your interest in our work!

Why don't you just remove these two arguments from your json?

As far as I understand, this question is about general definition of arguments with default of `None` values, and is not specific to our project. Do you have a better suggestion?

Best,
Uri

**Comment by urialon** [comment]
I'm closing this issue just to make sure we respond to all issues, but feel free to re-open it if you have any questions!
