### ISSUE TITLE
Support multilingual model like mt0, mBart ?

### ISSUE THREAD

**Issue by trannhatquy** [abertsch72/unlimiformer#18]
Can you add the support of multilingual model like mt0, mBart,... in unlimiformer ? This would be supportive for other languages

**Comment by trannhatquy** [comment]
Can anyone help me with the PR ? Thanks a lot

**Comment by urialon** [comment]
Hi @trannhatquy ,
Thank you for your interest in our work!

Does mBart have the same architecture as BART?
If so, it should be very easy to support it, by changing `BartForConditionalGeneration` to `MBartForConditionalGeneration` everywhere.

Best,
Uri
