### ISSUE TITLE
Question about decoder models

### ISSUE THREAD

**Issue by flozi00** [abertsch72/unlimiformer#2]
Great work, i just took a look to the code and found parts where you declare mappings containing gpt2
Models like opt should be adaptable too i think, but what about gpt neox, which only has `query_key_value` instead of query, key, value seperated layers ?
It would be interesting for open-assistant project and if it works it would have huge potential

**Comment by urialon** [comment]
Hi @flozi00 ,
Thank you for your interest in our work and for your kind words!

Initially, we experimented with Unlimiformer-GPT2, but after some time we decided to focus on encoder-decoder models, so the code no longer supports GPT2, and we will clean the GPT2 remainings.

Best,
Uri

**Comment by flozi00** [comment]
Then Flan-t5 could be still interesting and as far as i see it is supported
Do you think about converting the repo to an installable package ?
So its possible to install from github source or pypi instead of copy paste the files ?

**Comment by urialon** [comment]
Yes, definitely, once we converge to a stable version.

**Comment by SharkWipf** [comment]
So is there anything practically preventing this work from being applied to decoder-only models? 
This work is great for encoder-decoder models, but if it'd also be applicable to current decoder-only models, I feel the whole LLM playing field would suddenly change. 
Pair this work with a (decoder-only) model like LLAMA (or open source alternatives), and you'd be able to feed entire codebases into it and do codebase-wide analysis/code gen. 
Add an agent framework around it and it would run circles around any current agent design.

If this work could be applied/adapted to current decoder-only models I think that'd be huge, as that's where most of the current hype is.

**Comment by urialon** [comment]
There's nothing that practically prevents this from being applied to decoder-only models.
Just implementation and making sure that the right tensors fall into the right locations.

**Comment by urialon** [comment]
Hey @flozi00 ,

Unlimiformer now supports Flan-T5, Llama and Llama-2 (and all their derivatives)!

Check it out, and let us know if you have any questions!
https://github.com/abertsch72/unlimiformer#august-2023---unlimiformer-now-supports-llama-2-and-all-its-derivatives

Best,
Uri
