### ISSUE TITLE
ImportError: cannot import name 'Unlimiformer' from 'unlimiformer'

### ISSUE THREAD

**Issue by yungsinatra0** [abertsch72/unlimiformer#24]
Hi, I've been trying to run inference using the [model checkpoints on HF](https://huggingface.co/abertsch/unlimiformer-bart-govreport-alternating) by following the code in [inference-example.py](https://github.com/abertsch72/unlimiformer/blob/main/src/inference-example.py).

I'm using Google Colab and I'm cloning the whole repository. However, when I try to run the code, I get the following error: 
```
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-9-ea5aa8573cba>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from unlimiformer import Unlimiformer
      2 from random_training_unlimiformer import RandomTrainingUnlimiformer
      3 from usage import UnlimiformerArguments, training_addin
      4 
      5 from transformers import BartForConditionalGeneration, AutoTokenizer

ImportError: cannot import name 'Unlimiformer' from 'unlimiformer' (unknown location)


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

I've tried multiple things but nothing seems to work:

- Restarting runtime
- Deleting runtime & creating a new one
- Adding the directory to PATH
- Changing to directory using `%cd /content/unlimiformer/src`
- Moving the files to `/content/`

I'm not sure what I'm missing here. It seems to be such a minor issue but I'm out here pulling my hair out trying to figure why it isn't working. If someone can help me out I'd really appreciate it. Thanks!

**Comment by SharkWipf** [comment]
You need src/unlimiformer.py to be in the same folder as your project (or have it installed in your Python env) for it to be able to import it.

**Comment by yungsinatra0** [comment]
What do you mean by having it in the same folder as my project?

**Comment by urialon** [comment]
Hi @yungsinatra0 ,
Thank you for your interest in our work!

Does it work if you `cd src`?

Uri

**Comment by yungsinatra0** [comment]
Hi @urialon!

No, it doesn't. I've tried `cd src`, and also using `os.chdir()` and both do not seem to work.

**Comment by yungsinatra0** [comment]
@urialon I have done that as well.

**Comment by SharkWipf** [comment]
> from unlimiformer import Unlimiformer

This line in the code:
`from unlimiformer import Unlimiformer`
Means Python looks for, in this case, a file called `unlimiformer.py`, in the same folder your script (not you yourself) is in.
As long as this file exists in the same folder as your script, and hasn't been modified, it should resolve this specific error.

**Comment by yungsinatra0** [comment]
@SharkWipf I'm running this in Google Colab (jupyter notebook), so in this case the script is in a cell that is being executed. Could this cause the issue?

**Comment by SharkWipf** [comment]
I'm not too familiar with Colab/Jupyter so I can't say too much about that. But all the same, if you either ship unlimiformer.py with your project in the same folder, or copy it to the same folder as your script in the Jupyter notebook, it _should_ work.

**Comment by yungsinatra0** [comment]
@SharkWipf that's the problem, technically it _should_ be working, but for some reason it isn't, and I'm not sure why.

![image](https://github.com/abertsch72/unlimiformer/assets/16123801/916607d7-2d67-413c-b191-da0aea3d120a)

**Comment by urialon** [comment]
Hi @yungsinatra0 ,

Is this a problem only with this project, or does it happen if you create any python file and try to import classes from it?

**Comment by yungsinatra0** [comment]
@urialon I haven't tried creating a python file. I wanted to avoid that as I wanted to be able to see the code I'm running in each cell, but I'll give this option a try.

**Comment by urialon** [comment]
You can also just copy the entire `unlimiformer.py` file into a new cell and run it

**Comment by yungsinatra0** [comment]
@SharkWipf I did try that previously, here's the output from `sys.path`:

```
['/content', '/env/python', '/usr/lib/python310.zip', '/usr/lib/python3.10', '/usr/lib/python3.10/lib-dynload', '', '/usr/local/lib/python3.10/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.10/dist-packages/IPython/extensions', '/root/.ipython', '/content/unlimiformer/src/unlimiformer/src', '/content/unlimiformer/src/unlimiformer/src', '/content/unlimiformer/src']
```

(please ignore the weird paths, I'm not sure how I added them there)

I tried adding both `/content/unlimiformer/src` and `/content/unlimiformer` (you don't see the 2nd cause I deleted & restarted the runtime)

**Comment by yungsinatra0** [comment]
@urialon @SharkWipf I've just tried it again and it works now... this is very weird. I hope I'm not going to have this issue anymore! Thanks for helping me out!

**Comment by urialon** [comment]
Great, let us know if you have any more questions @yungsinatra0 !

@SharkWipf - thank you for your help and involvement!
