### ISSUE TITLE
run.py referencing missing file

### ISSUE THREAD

**Issue by stakodiak** [abertsch72/unlimiformer#3]
https://github.com/abertsch72/unlimiformer/blob/main/src/run.py#L72

Should this be checked into the repo or is it only meant to be read and not executed?

**Comment by urialon** [comment]
Hi @stakodiak ,
Thank you for your interest in our work!

Sorry, I will fix this and include all the needed files.

Best,
Uri

**Comment by urialon** [comment]
Fixed! Please let us know if you have any questions or problems @stakodiak .

Best,
Uri

**Comment by urialon** [comment]
I'm closing this issue just to make sure we respond to all issues, but feel free to re-open it if you have any questions!
