### ISSUE TITLE
knn_args, unlimiformer_args, tokenizer is not defined

### ISSUE THREAD

**Issue by laeljh** [abertsch72/unlimiformer#32]
Hi, I'm trying to deploy unlimiformer on my local machine. 
I cloned src folder into my source folder and installed the dependencies. 
When I open usage.py I see a bunch of problems:
![image](https://github.com/abertsch72/unlimiformer/assets/56128558/c1c61b06-5353-48a7-9c2b-c7917e54cd52)
![image](https://github.com/abertsch72/unlimiformer/assets/56128558/532c2299-a743-4731-93af-4b7d7b685074)

What am I missing here? I followed the instructions in the repo.

**Comment by abertsch72** [comment]
Hi @laeljh -- thanks for the interest in our work!

The function in `usage.py` is an example of a code snippet you could add in to your own training pipeline to integrate Unlimiformer. You'd have to instantiate your own UnlimiformerArguments object with the arguments you intend to use, and that would be the `unlimiformer_args` variable that you'd use with this logic. (The mention of `knn_args` is a mistake, though-- I've updated that to also be `unlimiformer_args`. )

If you want to work from a more self-contained example, you can try using `run.py` or `inference_example.py` using [these instructions](https://github.com/abertsch72/unlimiformer/tree/main#getting-started).
