### ISSUE TITLE
Not really an issue - TrainingArguments are now immutable

### ISSUE THREAD

**Issue by 9au5a** [abertsch72/unlimiformer#35]
See  https://discuss.huggingface.co/t/trainingarguments-now-immutable-why/52565    
and the nice solution https://github.com/huggingface/trl/pull/682

Quick fix if anybody has latest version too (& wants to run run.py lol):

1. In line 39 add 'replace'
2.  Replace line 705 by "training_args = replace(training_args, eval_fraction=min(training_args.eval_fraction, n))"
3. & analogous line 710 by "training_args = replace(training_args, eval_fraction=training_args.eval_fraction / n)"

PS: I also had some troubles with wandb and had to replace "fork" with "thread" in line 413, but I didn't really look up what exactly it was about.

Best, 
Paula

**Comment by urialon** [comment]
Thanks @9au5a , and thank you for your interest in our work!

If you manage to do this upgrade, we would love to accept a pull request.

Best,
Uri

**Comment by 9au5a** [comment]
Done
