### ISSUE TITLE
I have created a LinkedIn post for this repo.

### ISSUE THREAD

**Issue by hemangjoshi37a** [abertsch72/unlimiformer#9]
I found the work done under this repo is very much ground breaking , and that's why I though to create a Linkedin post to bring it to public eyes.
Here is the link to my original post : https://www.linkedin.com/posts/hemang-joshi-046746aa_home-activity-7061716941949796352-ztHP?utm_source=share&utm_medium=member_desktop

Please if you like the post then please help me by sharing by profile or my website with your friends.

Thanks,
Have a nice day
Hemang Joshi
Https://hjlabs.in

**Comment by urialon** [comment]
Hi @hemangjoshi37a ,
Thank you for your interest in our work and publicizing it!

I sent you a connection request on LinkedIn!

Best,
Uri

**Comment by hemangjoshi37a** [comment]
@urialon 
@DanielShemesh is one of my customers that is from Technion University. You might know him as you also have studied from Technion.
